from __future__ import annotations

DEFAULT_SHOT_COUNT = 10
DEFAULT_KEYFRAME_COUNT = 4
DEFAULT_FPS = 12
DEFAULT_TTS_VOICE = "zh-CN-YunxiNeural"
REAL_VIDEO_SEGMENT_SECONDS = 5
REAL_VIDEO_ASSET_MAX_WAIT_SECONDS = 120
REAL_VIDEO_ASSET_POLL_INTERVAL_SECONDS = 6
VIDEO_MOTION_SCORE_THRESHOLD = 0.0025
REAL_VIDEO_FALLBACK_WARNING_RATIO = 0.6
DEFAULT_SMOKE_TEST_TARGET_DURATION_SECONDS = 60.0
MIN_CHAPTER_DURATION_SECONDS = 24.0
MAX_CHAPTER_DURATION_SECONDS = 120.0
