import type { ProjectSummary, WorkspaceData } from "../../types/api";

export const sampleProjects: ProjectSummary[] = [
  {
    id: -1,
    name: "示例项目：斗气试制线",
    description: "当前为无后端数据时的展示模式。",
    status: "sample",
    created_at: "2026-04-03T09:00:00Z",
    updated_at: "2026-04-03T09:00:00Z",
  },
];

export const sampleWorkspace: WorkspaceData = {
  authSession: {
    auth_enabled: true,
    email: "admin@ai-manga.local",
    display_name: "Factory Admin",
    role: "admin",
  },
  settingsOverview: {
    auth: {
      enabled: true,
      bootstrap_accounts: [
        { email: "admin@ai-manga.local", display_name: "Factory Admin", role: "admin", status: "active" },
        { email: "reviewer@ai-manga.local", display_name: "Factory Reviewer", role: "reviewer", status: "active" },
        { email: "viewer@ai-manga.local", display_name: "Factory Viewer", role: "viewer", status: "active" },
      ],
    },
    runtime: {
      environment: "sample",
      default_routing_mode: "smart",
      archive_targets: ["local-archive", "object-storage", "quark-pan"],
      object_storage_mode: "s3",
      quark_pan_mode: "api",
      aliyundrive_mode: "mirror",
    },
    storage_targets: [
      {
        archive_type: "local-archive",
        mode: "mirror",
        location: "/data/archives/local",
        remote_base_url: null,
        is_ready: true,
        readiness_reason: "Local archive ready.",
      },
      {
        archive_type: "object-storage",
        mode: "s3",
        location: "https://oss.example.internal",
        remote_base_url: "s3://ai-manga-factory",
        is_ready: true,
        readiness_reason: "S3 credentials are configured.",
      },
      {
        archive_type: "quark-pan",
        mode: "api",
        location: "/secrets/quark_pan",
        remote_base_url: "quark://AI-Manga-Factory",
        is_ready: true,
        readiness_reason: "Quark Pan API credentials are configured.",
      },
    ],
    providers: [
      {
        id: 1,
        provider_key: "ark-story",
        provider_type: "llm",
        routing_mode: "smart",
        is_enabled: true,
        priority: 150,
        budget_threshold: 85,
        config: { vendor: "ark", model: "Doubao-Seed-1.6" },
      },
      {
        id: 2,
        provider_key: "llm-story",
        provider_type: "llm",
        routing_mode: "smart",
        is_enabled: true,
        priority: 100,
        budget_threshold: 90,
        config: { vendor: "fallback-local" },
      },
      {
        id: 3,
        provider_key: "vidu-primary",
        provider_type: "video",
        routing_mode: "manual",
        is_enabled: true,
        priority: 120,
        budget_threshold: 80,
        config: { vendor: "vidu" },
      },
    ],
  },
  auditLogs: [
    {
      id: 1,
      actor_user_id: 1,
      actor_email: "admin@ai-manga.local",
      actor_role: "admin",
      action: "patch:settings",
      resource_type: "settings",
      resource_id: "providers",
      request_method: "PATCH",
      request_path: "/api/v1/settings/providers/ark-story",
      response_status: 200,
      outcome: "success",
      detail: { client: "127.0.0.1" },
      created_at: "2026-04-04T10:20:00Z",
      updated_at: "2026-04-04T10:20:00Z",
    },
    {
      id: 2,
      actor_user_id: 2,
      actor_email: "reviewer@ai-manga.local",
      actor_role: "reviewer",
      action: "post:reviews",
      resource_type: "reviews",
      resource_id: null,
      request_method: "POST",
      request_path: "/api/v1/reviews",
      response_status: 201,
      outcome: "success",
      detail: { client: "127.0.0.1" },
      created_at: "2026-04-04T10:15:00Z",
      updated_at: "2026-04-04T10:15:00Z",
    },
  ],
  overview: {
    project_name: "示例项目：斗气试制线",
    status: "sample",
    summary: "当前没有真实项目数据，控制塔已切换到示例模式，便于预览布局与交互结构。",
    chapter_progress: [
      { label: "章节总数", value: "24", tone: "neutral" },
      { label: "进行中", value: "7", tone: "warning" },
      { label: "异常章节", value: "2", tone: "danger" },
      { label: "已完成", value: "13", tone: "success" },
    ],
    asset_health: [
      { label: "角色卡", value: "12", tone: "neutral" },
      { label: "场景资产", value: "9", tone: "neutral" },
      { label: "音色资产", value: "8", tone: "neutral" },
      { label: "多视图参考", value: "37", tone: "neutral" },
    ],
    provider_usage: [
      { label: "ark-story", value: "5400 tokens", tone: "success" },
      { label: "llm-story", value: "12800 tokens", tone: "neutral" },
      { label: "vidu-primary", value: "74 credits", tone: "warning" },
      { label: "voice-clone-main", value: "33 credits", tone: "neutral" },
    ],
    initialization_progress: [
      { label: "原文导入", value: "imported", tone: "success" },
      { label: "摘要生成", value: "completed", tone: "success" },
      { label: "剧本初稿", value: "completed", tone: "success" },
      { label: "角色初稿", value: "6", tone: "success" },
      { label: "场景初稿", value: "4", tone: "success" },
    ],
  },
  chapters: [
    {
      id: 101,
      project_id: -1,
      chapter_number: 1,
      title: "乌坦城开篇",
      summary: "交代主角处境与初始人物关系。",
      status: "completed",
      created_at: "2026-04-03T09:00:00Z",
      updated_at: "2026-04-03T09:00:00Z",
      pipeline_states: [
        { id: 1, stage_key: "storyboard", status: "completed", detail: null, created_at: "", updated_at: "" },
        { id: 2, stage_key: "video", status: "completed", detail: null, created_at: "", updated_at: "" },
        { id: 3, stage_key: "voice", status: "completed", detail: null, created_at: "", updated_at: "" },
        { id: 4, stage_key: "finalize", status: "completed", detail: null, created_at: "", updated_at: "" },
      ],
    },
    {
      id: 102,
      project_id: -1,
      chapter_number: 2,
      title: "天赋落差",
      summary: "分镜已过审，视频阶段等待补点数。",
      status: "in_progress",
      created_at: "2026-04-03T09:00:00Z",
      updated_at: "2026-04-03T09:00:00Z",
      pipeline_states: [
        { id: 5, stage_key: "storyboard", status: "completed", detail: null, created_at: "", updated_at: "" },
        { id: 6, stage_key: "video", status: "failed", detail: "Vidu 额度不足", created_at: "", updated_at: "" },
        { id: 7, stage_key: "voice", status: "not_started", detail: null, created_at: "", updated_at: "" },
        { id: 8, stage_key: "finalize", status: "not_started", detail: null, created_at: "", updated_at: "" },
      ],
    },
  ],
  characters: [
    {
      id: 11,
      project_id: -1,
      name: "萧炎",
      appearance: "黑发、冷色系服装、少年感强。",
      personality: "倔强、隐忍、成长型。",
      lora_path: "loras/xiao-yan.safetensors",
      review_status: "approved",
      reference_images: [
        {
          id: 1,
          view_type: "front",
          asset_path: "references/xiao-yan-front.png",
          notes: "正脸标准照",
          created_at: "",
          updated_at: "",
        },
      ],
      created_at: "",
      updated_at: "",
    },
    {
      id: 12,
      project_id: -1,
      name: "药老",
      appearance: "白发长袍、半透明灵体感。",
      personality: "沉稳、导师型、压场。",
      lora_path: "loras/yao-lao.safetensors",
      review_status: "reviewing",
      reference_images: [],
      created_at: "",
      updated_at: "",
    },
  ],
  scenes: [
    {
      id: 31,
      project_id: -1,
      name: "乌坦城议事堂",
      baseline_prompt: "乌坦城议事堂，石柱高耸，暖金火光，保持家族会议的压迫感。",
      continuity_guardrails: "保持主门朝向、议事桌位置和人物站位关系一致。",
      review_status: "draft",
      created_at: "",
      updated_at: "",
    },
    {
      id: 32,
      project_id: -1,
      name: "后山石台",
      baseline_prompt: "后山石台，夜色偏蓝，月光切出人物轮廓，空间要安静克制。",
      continuity_guardrails: "保持石台高度、树影方向和月光来源一致。",
      review_status: "draft",
      created_at: "",
      updated_at: "",
    },
  ],
  voices: [
    {
      id: 21,
      project_id: -1,
      character_name: "萧炎",
      voice_key: "voice-xiao-yan-01",
      provider_key: "voice-clone-main",
      tone_description: "少年、克制、带冷感。",
      created_at: "",
      updated_at: "",
    },
    {
      id: 22,
      project_id: -1,
      character_name: "药老",
      voice_key: "voice-yao-lao-01",
      provider_key: "voice-clone-main",
      tone_description: "老练、低频、可信赖。",
      created_at: "",
      updated_at: "",
    },
  ],
  projectInitialization: {
    project_id: -1,
    status: "completed",
    stage_cards: [
      { label: "原文导入", value: "imported", tone: "success" },
      { label: "摘要生成", value: "completed", tone: "success" },
      { label: "剧本初稿", value: "completed", tone: "success" },
      { label: "角色初稿", value: "6", tone: "success" },
      { label: "场景初稿", value: "4", tone: "success" },
    ],
    generation_trace: {
      generation_mode: "model",
      routing_mode: "smart",
      manual_provider: null,
      resolved_provider_key: "ark-story",
      provider_candidates: ["ark-story", "llm-story"],
      provider_attempts: [
        { provider_key: "ark-story", status: "completed", error_message: null },
      ],
      usage_amount: 1840,
      usage_unit: "tokens",
    },
    source: {
      id: 1,
      project_id: -1,
      source_title: "斗气试制线原文",
      source_type: "novel_text",
      import_status: "imported",
      chapter_count: 24,
      content_preview: "萧炎在乌坦城的议事堂里迎来命运拐点，家族压力、药老现身和修行转折开始汇聚。",
      created_at: "2026-04-03T09:00:00Z",
      updated_at: "2026-04-03T09:00:00Z",
    },
    summary: {
      id: 2,
      project_id: -1,
      status: "completed",
      summary_body: "前期主线聚焦乌坦城压迫、主角失势与药老介入，强调成长起点和身份反差。",
      highlights: [
        "第1章：乌坦城建立主角处境。",
        "第2章：药老介入并开启夜谈。",
      ],
      created_at: "2026-04-03T09:02:00Z",
      updated_at: "2026-04-03T09:02:00Z",
    },
    script: {
      id: 3,
      project_id: -1,
      status: "completed",
      title: "斗气试制线 项目剧本初稿",
      script_body: "## 第1章 乌坦城风起\n- 剧情摘要：建立主角处境与家族压力。\n- 角色焦点：萧炎、药老。\n- 场景焦点：乌坦城议事堂。\n",
      created_at: "2026-04-03T09:03:00Z",
      updated_at: "2026-04-03T09:03:00Z",
    },
    chapters: [
      {
        id: 101,
        project_id: -1,
        chapter_number: 1,
        title: "乌坦城开篇",
        summary: "交代主角处境与初始人物关系。",
        status: "completed",
        created_at: "2026-04-03T09:00:00Z",
        updated_at: "2026-04-03T09:00:00Z",
        pipeline_states: [
          { id: 1, stage_key: "storyboard", status: "completed", detail: null, created_at: "", updated_at: "" },
          { id: 2, stage_key: "video", status: "completed", detail: null, created_at: "", updated_at: "" },
          { id: 3, stage_key: "voice", status: "completed", detail: null, created_at: "", updated_at: "" },
          { id: 4, stage_key: "finalize", status: "completed", detail: null, created_at: "", updated_at: "" },
        ],
      },
      {
        id: 102,
        project_id: -1,
        chapter_number: 2,
        title: "天赋落差",
        summary: "分镜已过审，视频阶段等待补点数。",
        status: "in_progress",
        created_at: "2026-04-03T09:00:00Z",
        updated_at: "2026-04-03T09:00:00Z",
        pipeline_states: [
          { id: 5, stage_key: "storyboard", status: "completed", detail: null, created_at: "", updated_at: "" },
          { id: 6, stage_key: "video", status: "failed", detail: "Vidu 额度不足", created_at: "", updated_at: "" },
          { id: 7, stage_key: "voice", status: "not_started", detail: null, created_at: "", updated_at: "" },
          { id: 8, stage_key: "finalize", status: "not_started", detail: null, created_at: "", updated_at: "" },
        ],
      },
    ],
    character_drafts: [
      {
        id: 11,
        project_id: -1,
        name: "萧炎",
        appearance: "黑发、冷色系服装、少年感强。",
        personality: "倔强、隐忍、成长型。",
        lora_path: "loras/xiao-yan.safetensors",
        review_status: "approved",
        reference_images: [
          {
            id: 1,
            view_type: "front",
            asset_path: "references/xiao-yan-front.png",
            notes: "正脸标准照",
            created_at: "",
            updated_at: "",
          },
        ],
        created_at: "",
        updated_at: "",
      },
      {
        id: 12,
        project_id: -1,
        name: "药老",
        appearance: "白发长袍、半透明灵体感。",
        personality: "沉稳、导师型、压场。",
        lora_path: "loras/yao-lao.safetensors",
        review_status: "reviewing",
        reference_images: [],
        created_at: "",
        updated_at: "",
      },
    ],
    scene_drafts: [
      {
        id: 31,
        project_id: -1,
        name: "乌坦城议事堂",
        baseline_prompt: "乌坦城议事堂，石柱高耸，暖金火光，保持家族会议的压迫感。",
        continuity_guardrails: "保持主门朝向、议事桌位置和人物站位关系一致。",
        review_status: "draft",
        created_at: "",
        updated_at: "",
      },
      {
        id: 32,
        project_id: -1,
        name: "后山石台",
        baseline_prompt: "后山石台，夜色偏蓝，月光切出人物轮廓，空间要安静克制。",
        continuity_guardrails: "保持石台高度、树影方向和月光来源一致。",
        review_status: "draft",
        created_at: "",
        updated_at: "",
      },
    ],
  },
  artifacts: [
    {
      id: 501,
      project_id: -1,
      chapter_id: 101,
      job_run_id: 41,
      step_key: "storyboard",
      title: "章节 1 分镜预览",
      media_kind: "storyboard",
      provider_key: "llm-story",
      status: "ready",
      mime_type: "text/html",
      artifact_path: "project_-1/chapter_101/job_41/storyboard-artifact.html",
      preview_path: "project_-1/chapter_101/job_41/storyboard-preview.html",
      preview_url: "/api/v1/previews/artifacts/501",
      size_bytes: 2048,
      artifact_metadata: {
        playback_hint: "已生成可访问的 HTML 分镜预览。",
      },
      archives: [
        {
          id: 701,
          archive_type: "local-archive",
          archive_path: "local-archive/project_-1/chapter_101/job_41/storyboard-artifact.html",
          index_key: "local-archive:501",
          status: "archived",
          remote_url: null,
          checksum_sha256: "7e2f9e28aa5f1dc9d2c6b6237a4bfbe8dc1f5b60b4f4c9db9d5dc8f0a6e1b390",
          created_at: "",
          updated_at: "",
        },
        {
          id: 702,
          archive_type: "object-storage",
          archive_path: "ai-manga-factory/project_-1/chapter_101/job_41/storyboard-artifact.html",
          index_key: "object-storage:501",
          status: "archived",
          remote_url: "s3://ai-manga-factory/project_-1/chapter_101/job_41/storyboard-artifact.html",
          checksum_sha256: "7e2f9e28aa5f1dc9d2c6b6237a4bfbe8dc1f5b60b4f4c9db9d5dc8f0a6e1b390",
          created_at: "",
          updated_at: "",
        },
      ],
      sync_runs: [
        {
          id: 801,
          artifact_id: 501,
          archive_type: "object-storage",
          status: "completed",
          summary: "Archive sync finished for 1 target.",
          error_message: null,
          worker_id: "worker-demo-archive",
          attempt_count: 1,
          started_at: "2026-04-03T09:04:00Z",
          finished_at: "2026-04-03T09:04:03Z",
          created_at: "2026-04-03T09:03:58Z",
          updated_at: "2026-04-03T09:04:03Z",
        },
      ],
      created_at: "",
      updated_at: "",
    },
    {
      id: 502,
      project_id: -1,
      chapter_id: 101,
      job_run_id: 41,
      step_key: "voice",
      title: "章节 1 配音预览",
      media_kind: "audio",
      provider_key: "voice-clone-main",
      status: "ready",
      mime_type: "audio/wav",
      artifact_path: "project_-1/chapter_101/job_41/voice-artifact.wav",
      preview_path: "project_-1/chapter_101/job_41/voice-preview.wav",
      preview_url: "/api/v1/previews/artifacts/502",
      size_bytes: 32768,
      artifact_metadata: {
        playback_hint: "已生成可直接播放的音频预览。",
      },
      archives: [
        {
          id: 703,
          archive_type: "local-archive",
          archive_path: "local-archive/project_-1/chapter_101/job_41/voice-artifact.wav",
          index_key: "local-archive:502",
          status: "archived",
          remote_url: null,
          checksum_sha256: "f1f5118572f1c6d88871b0ff08f9f8f5ca0e6f3af1efb0d0c6d88af76b9e12d4",
          created_at: "",
          updated_at: "",
        },
        {
          id: 704,
          archive_type: "quark-pan",
          archive_path: "project_-1/chapter_101/job_41/voice-artifact.wav",
          index_key: "quark-pan:502",
          status: "archived",
          remote_url: "quark://AI-Manga-Factory/project_-1/chapter_101/job_41/voice-artifact.wav",
          checksum_sha256: "f1f5118572f1c6d88871b0ff08f9f8f5ca0e6f3af1efb0d0c6d88af76b9e12d4",
          created_at: "",
          updated_at: "",
        },
      ],
      sync_runs: [
        {
          id: 802,
          artifact_id: 502,
          archive_type: "quark-pan",
          status: "queued",
          summary: "Archive sync task queued.",
          error_message: null,
          worker_id: null,
          attempt_count: 0,
          started_at: null,
          finished_at: null,
          created_at: "2026-04-03T09:05:00Z",
          updated_at: "2026-04-03T09:05:00Z",
        },
      ],
      created_at: "",
      updated_at: "",
    },
  ],
  storageTargets: [
    {
      archive_type: "local-archive",
      mode: "mirror",
      location: "/data/archives/local-archive",
      remote_base_url: null,
      is_ready: true,
      readiness_reason: "Local archive mirror directory is available.",
    },
    {
      archive_type: "object-storage",
      mode: "mirror",
      location: "/data/archives/object-storage",
      remote_base_url: "s3://ai-manga-factory",
      is_ready: true,
      readiness_reason: "Bucket and mirror root are configured.",
    },
    {
      archive_type: "quark-pan",
      mode: "mirror",
      location: "/data/archives/quark-pan",
      remote_base_url: "quark://AI-Manga-Factory",
      is_ready: true,
      readiness_reason: "Quark Pan mirror root is configured.",
    },
  ],
  workflows: [
    {
      id: 31,
      project_id: -1,
      name: "章节标准流水线",
      description: "分镜 -> 视频 -> 配音 -> 成片",
      routing_mode: "smart",
      created_at: "",
      updated_at: "",
      spec: {
        nodes: [
          { key: "storyboard", title: "分镜", provider_type: "llm", checkpointable: true },
          { key: "video", title: "视频", provider_type: "video", checkpointable: true },
          { key: "voice", title: "配音", provider_type: "voice", checkpointable: true },
        ],
        edges: [
          { source: "storyboard", target: "video" },
          { source: "video", target: "voice" },
        ],
      },
    },
  ],
  jobs: [
    {
      id: 41,
      project_id: -1,
      chapter_id: 101,
      workflow_id: 31,
      execution_mode: "sync",
      routing_mode: "smart",
      status: "completed",
      current_step_key: null,
      summary: "章节 1 成功完成。",
      error_message: null,
      request_payload: {},
      created_at: "2026-04-03T09:00:00Z",
      updated_at: "2026-04-03T09:10:00Z",
      checkpoints: [],
      steps: [
        {
          id: 51,
          sequence_no: 1,
          step_key: "storyboard",
          step_name: "分镜",
          provider_type: "llm",
          provider_key: "ark-story",
          status: "completed",
          usage_amount: 1200,
          usage_unit: "tokens",
          output_snapshot: {
            provider_candidates: ["ark-story", "llm-story"],
            resolved_provider_key: "ark-story",
            provider_attempts: [{ provider_key: "ark-story", status: "completed" }],
            mime_type: "text/html; charset=utf-8",
          },
          error_message: null,
          created_at: "2026-04-03T09:02:00Z",
          updated_at: "2026-04-03T09:02:20Z",
        },
        {
          id: 54,
          sequence_no: 2,
          step_key: "video",
          step_name: "视频",
          provider_type: "video",
          provider_key: "ark-video",
          status: "completed",
          usage_amount: 18,
          usage_unit: "credits",
          output_snapshot: {
            provider_candidates: ["ark-video", "vidu-primary"],
            resolved_provider_key: "ark-video",
            provider_attempts: [{ provider_key: "ark-video", status: "completed" }],
            mime_type: "video/mp4",
          },
          error_message: null,
          created_at: "2026-04-03T09:03:00Z",
          updated_at: "2026-04-03T09:03:28Z",
        },
      ],
    },
    {
      id: 42,
      project_id: -1,
      chapter_id: 102,
      workflow_id: 31,
      execution_mode: "sync",
      routing_mode: "smart",
      status: "failed",
      current_step_key: "video",
      summary: "章节 2 在视频阶段失败。",
      error_message: "Vidu 额度不足",
      request_payload: {},
      created_at: "2026-04-03T09:00:00Z",
      updated_at: "2026-04-03T09:14:00Z",
      checkpoints: [
        {
          id: 61,
          step_key: "video",
          payload: {},
          resume_cursor: "video",
          created_at: "",
          updated_at: "",
        },
      ],
      steps: [
        {
          id: 52,
          sequence_no: 1,
          step_key: "storyboard",
          step_name: "分镜",
          provider_type: "llm",
          provider_key: "llm-story",
          status: "completed",
          usage_amount: 1500,
          usage_unit: "tokens",
          output_snapshot: {
            provider_candidates: ["ark-story", "llm-story"],
            resolved_provider_key: "llm-story",
            provider_attempts: [
              {
                provider_key: "ark-story",
                status: "failed",
                error_message: "Ark text quota exhausted",
              },
              {
                provider_key: "llm-story",
                status: "completed",
              },
            ],
            mime_type: "text/html; charset=utf-8",
          },
          error_message: null,
          created_at: "2026-04-03T09:11:00Z",
          updated_at: "2026-04-03T09:11:24Z",
        },
        {
          id: 53,
          sequence_no: 2,
          step_key: "video",
          step_name: "视频",
          provider_type: "video",
          provider_key: "vidu-primary",
          status: "failed",
          usage_amount: 0,
          usage_unit: "credits",
          output_snapshot: {
            provider_candidates: ["ark-video", "vidu-primary"],
            resolved_provider_key: "vidu-primary",
            provider_attempts: [
              {
                provider_key: "ark-video",
                status: "failed",
                error_message: "Ark video quota exhausted",
              },
              {
                provider_key: "vidu-primary",
                status: "failed",
                error_message: "Vidu 额度不足",
              },
            ],
            mime_type: "text/html; charset=utf-8",
          },
          error_message: "Vidu 额度不足",
          created_at: "2026-04-03T09:12:00Z",
          updated_at: "2026-04-03T09:14:00Z",
        },
      ],
    },
  ],
  monitoring: {
    items: [
      {
        provider_key: "ark-story",
        provider_type: "llm",
        routing_mode: "smart",
        budget_threshold: 85,
        consumed: 5400,
        usage_unit: "tokens",
        alert_status: "healthy",
      },
      {
        provider_key: "ark-video",
        provider_type: "video",
        routing_mode: "smart",
        budget_threshold: 80,
        consumed: 32,
        usage_unit: "credits",
        alert_status: "healthy",
      },
      {
        provider_key: "llm-story",
        provider_type: "llm",
        routing_mode: "smart",
        budget_threshold: 85,
        consumed: 12800,
        usage_unit: "tokens",
        alert_status: "healthy",
      },
      {
        provider_key: "vidu-primary",
        provider_type: "video",
        routing_mode: "smart",
        budget_threshold: 80,
        consumed: 84,
        usage_unit: "credits",
        alert_status: "warning",
      },
    ],
    alerts: [
      {
        id: 301,
        alert_key: "provider-budget:vidu-primary",
        scope_type: "provider_budget",
        scope_key: "vidu-primary",
        severity: "warning",
        status: "active",
        title: "vidu-primary budget threshold exceeded",
        message: "vidu-primary has consumed 84 credits against threshold 80 credits.",
        detail: {
          provider_key: "vidu-primary",
          consumed: 84,
          budget_threshold: 80,
          usage_unit: "credits",
          ratio: 1.05,
        },
        first_triggered_at: "2026-04-03T09:13:00Z",
        last_triggered_at: "2026-04-03T09:14:00Z",
        resolved_at: null,
        created_at: "2026-04-03T09:13:00Z",
        updated_at: "2026-04-03T09:14:00Z",
      },
    ],
    workers: [
      {
        worker_id: "worker-main-01",
        worker_type: "hybrid",
        status: "idle",
        health_status: "healthy",
        last_seen_at: "2026-04-03T09:15:00Z",
        seconds_since_seen: 4,
        last_job_id: 42,
        detail: {
          last_task_type: "job",
        },
      },
      {
        worker_id: "worker-archive-01",
        worker_type: "archive-sync",
        status: "idle",
        health_status: "stale",
        last_seen_at: "2026-04-03T08:55:00Z",
        seconds_since_seen: 1240,
        last_job_id: null,
        detail: {
          last_task_type: "archive_sync",
        },
      },
    ],
    summary: {
      active_alerts: 1,
      healthy_workers: 1,
      stale_workers: 1,
      queued_jobs: 1,
      running_jobs: 0,
      failed_jobs: 1,
      resumable_jobs: 0,
      completed_jobs: 2,
    },
  },
  previews: {
    items: [
      {
        id: "41-storyboard",
        artifact_id: 501,
        job_id: 41,
        chapter_id: 101,
        stage_key: "storyboard",
        title: "章节 1 分镜预览",
        media_kind: "storyboard",
        status: "completed",
        provider_key: "ark-story",
        mime_type: "text/html",
        archive_status: "archived",
        archive_targets: ["local-archive", "object-storage"],
        playback_url: "/api/v1/previews/artifacts/501",
        playback_hint: "已生成可访问的 HTML 分镜预览。",
        updated_at: "2026-04-03T09:10:00Z",
      },
      {
        id: "42-video",
        artifact_id: 502,
        job_id: 42,
        chapter_id: 102,
        stage_key: "video",
        title: "章节 2 视频预览",
        media_kind: "video",
        status: "completed",
        provider_key: "ark-video",
        mime_type: "text/html",
        archive_status: "archived",
        archive_targets: ["local-archive", "object-storage"],
        playback_url: "/api/v1/previews/artifacts/502",
        playback_hint: "已生成可访问的镜头预览页，可继续替换为真实视频流。",
        updated_at: "2026-04-03T09:14:00Z",
      },
    ],
  },
  promptTemplates: [
    {
      id: 71,
      project_id: -1,
      workflow_key: "chapter-standard",
      template_version: "v3",
      template_body: "先锁定角色外观，再生成镜头节奏与动作指令。",
      feedback_count: 4,
      latest_score: 5,
      created_at: "2026-04-03T09:00:00Z",
      updated_at: "2026-04-03T10:00:00Z",
    },
  ],
  promptFeedback: [
    {
      id: 81,
      prompt_template_id: 71,
      job_run_id: 42,
      score: 4,
      correction_summary: "补充角色服装统一和转场提示。",
      corrected_prompt: "先锁定角色服装，再限制镜头切换速度和空间连续性。",
      created_at: "2026-04-03T10:00:00Z",
      updated_at: "2026-04-03T10:00:00Z",
    },
  ],
  sharedMemories: [
    {
      id: 91,
      project_id: -1,
      scope_type: "project",
      scope_key: "global-story-bible",
      memory_type: "continuity_rule",
      content: {
        rule: "萧炎前两章保持黑金主服装，不切换发型。",
        owner: "continuity-keeper",
      },
      created_at: "2026-04-03T09:30:00Z",
      updated_at: "2026-04-03T09:30:00Z",
    },
  ],
  reviewTasks: [
    {
      id: 101,
      project_id: -1,
      chapter_id: 102,
      review_stage: "script",
      review_type: "multi-agent",
      status: "completed",
      assigned_agents: ["logic-auditor", "continuity-keeper", "character-editor"],
      checklist: ["剧情逻辑", "角色一致性", "世界观约束"],
      findings_summary: "第二幕转场需要补足动机说明，并把场景锚点写得更明确。",
      result_payload: {
        blocking_status: "warning",
        severity: "medium",
        summary: "第二幕转场需要补足动机说明，并把场景锚点写得更明确。",
        findings: [
          {
            agent: "logic-auditor",
            title: "转场动机偏弱",
            severity: "medium",
            summary: "角色从议事堂切到后山石台时，触发原因还不够明确。",
            recommendation: "补一条角色即时动机或外部刺激，推动转场发生。",
          },
          {
            agent: "continuity-keeper",
            title: "场景锚点需要再固定",
            severity: "low",
            summary: "进入后山石台后，空间朝向和主光源提示还不够稳定。",
            recommendation: "补一条场景朝向或月光方向提示，稳住连续性。",
          },
        ],
        execution_trace: {
          generation_mode: "model",
          routing_mode: "smart",
          manual_provider: null,
          resolved_provider_key: "ark-story",
          provider_candidates: ["ark-story", "llm-story"],
          provider_attempts: [{ provider_key: "ark-story", status: "completed", error_message: null }],
          usage_amount: 860,
          usage_unit: "tokens",
        },
      },
      created_at: "2026-04-03T09:40:00Z",
      updated_at: "2026-04-03T09:40:00Z",
    },
  ],
};
